steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd ./iac/
        echo "BRANCH_NAME: $BRANCH_NAME"
        if [[ "$BRANCH_NAME" == "main" ]]; then
            terraform workspace new gcp-env-prod || terraform workspace select gcp-env-prod
            terraform workspace select gcp-env-prod
        elif [[ $BRANCH_NAME =~ ^feature\/ || $BRANCH_NAME == "develop" ]]; then
            terraform workspace new gcp-env-dev || terraform workspace select gcp-env-dev
        else
            echo "No matching branch tag found. Skipping Terraform execution."
        fi

        terraform init

        if [[ "$BRANCH_NAME" == "main" ]]; then
          terraform plan -var-file=gcp-env-prod.tfvars
        elif [[ $BRANCH_NAME =~ ^feature\/ || $BRANCH_NAME == "develop" ]]; then
          terraform plan -var-file=gcp-env-dev.tfvars
        else
          echo "No matching branch tag found. Skipping Terraform execution."
        fi
